### ISSUE TITLE
Display of thermal images of multiple cameras

### ISSUE THREAD

**Issue by Gyeen** [seekthermal/seekcamera-python#10]
How can I display thermal images of two cameras at the same time？The current program can connect multiple cameras at the same time, but only displays the screen of one of them.

**Comment by m-mead** [comment]
Hi @Gyeen, as is, the current `seekcamera-sdl.py` example renders frames from a single camera at a time. This is a design choice of the sample program, rather than a limitation `seekcamera-python` itself. 😊 

One possible strategy for rendering multiple cameras generically is to use a rendering pool to associate each `Renderer` object with one `SeekCamera` object. This is compared to the single `Renderer` used in `seekcamera-sdl.py`.

```python
renderer_pool = [Renderer()] * 16
manager.register_event_callback(on_event, renderer_pool)
```

and when a camera event occurs in `on_event`, handle it accordingly.

If you are only interested in rendering two cameras at once simultaneously, then a generalized rendering pool is probably overkill, and you can instead use a `Tuple[Renderer, Renderer]` to pass to the callback.

```python
renderers = (Renderer(), Renderer())
manager.register_event_callback(on_event, renderers)
```

and when a camera event occurs in `on_event`, handle it accordingly by checking `renderers[0]` and `renderers[1]`.

**Comment by Gyeen** [comment]
Thanks for the reply, I have solved this problem.
