### ISSUE TITLE
The temperature values output by the infrared camera

### ISSUE THREAD

**Issue by Gyeen** [seekthermal/seekcamera-python#12]
Dear, seekthermal
When I tried to put my hand in the field of view of the infrared camera and output the pixel temperature supported by `seekcamera-simple.py`, I found that the temperature of some areas of my hand was even lower than 25 degrees Celsius, which is obviously unreasonable. So I ask you whether the temperature detected by the infrared camera can be used for actual temperature measurement to help me determine the cause of this problem.
Thanks a lot.

**Comment by WDombrowski** [comment]
Seek Thermal OEM Moasic and Micro Core cameras are calibrated to give more accurate temperature readings. While items like the Seek Compact is used mostly for imagery since it has no thermographic accuracy specification. In general, thermal cameras are incredibly sensitive at seeing relative temperature differences and fairly good at reading absolute temperatures. Many customers add secondary calibration tables depending on their use case, product housing, and distance. Please visit https://www.thermal.com/OEM to learn more about Seek Thermal OEM Starter Kits.

In addition, it should be stated that skin temperatures are typically cooler than internal body temperatures. Your skin can actually reach extremely low temperatures 25C to 18C even is not that uncommon, especially if placed in cold and windy environments. This is why blackbodies are the best way to measure a thermal cameras accuracy.
